// AUTO-GENERATED — do not edit by hand.
// Regenerate after adding/removing files in public/images/gallery/.
// Source: Clay's job photos, optimized to 1400px / ~360KB each.
// Curated showcase: trimmed from 175 to 44 to remove near-duplicate / look-alike shots.

export const GALLERY_IMAGES: string[] = [
  '/images/gallery/rodas-001.jpg',
  '/images/gallery/rodas-002.jpg',
  '/images/gallery/rodas-006.jpg',
  '/images/gallery/rodas-009.jpg',
  '/images/gallery/rodas-015.jpg',
  '/images/gallery/rodas-018.jpg',
  '/images/gallery/rodas-025.jpg',
  '/images/gallery/rodas-031.jpg',
  '/images/gallery/rodas-033.jpg',
  '/images/gallery/rodas-035.jpg',
  '/images/gallery/rodas-040.jpg',
  '/images/gallery/rodas-044.jpg',
  '/images/gallery/rodas-045.jpg',
  '/images/gallery/rodas-050.jpg',
  '/images/gallery/rodas-061.jpg',
  '/images/gallery/rodas-065.jpg',
  '/images/gallery/rodas-070.jpg',
  '/images/gallery/rodas-086.jpg',
  '/images/gallery/rodas-099.jpg',
  '/images/gallery/rodas-100.jpg',
  '/images/gallery/rodas-101.jpg',
  '/images/gallery/rodas-106.jpg',
  '/images/gallery/rodas-108.jpg',
  '/images/gallery/rodas-109.jpg',
  '/images/gallery/rodas-115.jpg',
  '/images/gallery/rodas-118.jpg',
  '/images/gallery/rodas-121.jpg',
  '/images/gallery/rodas-122.jpg',
  '/images/gallery/rodas-124.jpg',
  '/images/gallery/rodas-144.jpg',
  '/images/gallery/rodas-145.jpg',
  '/images/gallery/rodas-146.jpg',
  '/images/gallery/rodas-150.jpg',
  '/images/gallery/rodas-153.jpg',
  '/images/gallery/rodas-154.jpg',
  '/images/gallery/rodas-156.jpg',
  '/images/gallery/rodas-157.jpg',
  '/images/gallery/rodas-158.jpg',
  '/images/gallery/rodas-160.jpg',
  '/images/gallery/rodas-166.jpg',
  '/images/gallery/rodas-167.jpg',
  '/images/gallery/rodas-171.jpg',
  '/images/gallery/rodas-173.jpg',
  '/images/gallery/rodas-174.jpg',
];
