// AUTO-GENERATED — do not edit by hand.
// Regenerate after adding/removing files in public/images/gallery/.
// Source photos: Clay's job photos, optimized to 1400px / ~350KB.

export const GALLERY_IMAGES: string[] = [
  '/images/gallery/rodas-01.jpg',
  '/images/gallery/rodas-02.jpg',
  '/images/gallery/rodas-03.jpg',
  '/images/gallery/rodas-04.jpg',
  '/images/gallery/rodas-05.jpg',
  '/images/gallery/rodas-06.jpg',
  '/images/gallery/rodas-07.jpg',
  '/images/gallery/rodas-08.jpg',
  '/images/gallery/rodas-09.jpg',
  '/images/gallery/rodas-10.jpg',
  '/images/gallery/rodas-11.jpg',
  '/images/gallery/rodas-12.jpg',
  '/images/gallery/rodas-13.jpg',
  '/images/gallery/rodas-14.jpg',
  '/images/gallery/rodas-15.jpg',
  '/images/gallery/rodas-16.jpg',
  '/images/gallery/rodas-17.jpg',
  '/images/gallery/rodas-18.jpg',
  '/images/gallery/rodas-19.jpg',
  '/images/gallery/rodas-20.jpg',
  '/images/gallery/rodas-21.jpg',
  '/images/gallery/rodas-22.jpg',
  '/images/gallery/rodas-23.jpg',
  '/images/gallery/rodas-24.jpg',
  '/images/gallery/rodas-25.jpg',
  '/images/gallery/rodas-26.jpg',
  '/images/gallery/rodas-27.jpg',
  '/images/gallery/rodas-28.jpg',
  '/images/gallery/rodas-29.jpg',
  '/images/gallery/rodas-30.jpg',
  '/images/gallery/rodas-31.jpg',
  '/images/gallery/rodas-32.jpg',
  '/images/gallery/rodas-33.jpg',
  '/images/gallery/rodas-34.jpg',
  '/images/gallery/rodas-35.jpg',
  '/images/gallery/rodas-36.jpg',
  '/images/gallery/rodas-37.jpg',
  '/images/gallery/rodas-38.jpg',
  '/images/gallery/rodas-39.jpg',
  '/images/gallery/rodas-40.jpg',
  '/images/gallery/rodas-41.jpg',
  '/images/gallery/rodas-42.jpg',
  '/images/gallery/rodas-43.jpg',
  '/images/gallery/rodas-44.jpg',
  '/images/gallery/rodas-45.jpg',
  '/images/gallery/rodas-46.jpg',
  '/images/gallery/rodas-47.jpg',
  '/images/gallery/rodas-48.jpg',
  '/images/gallery/rodas-49.jpg',
];

export const GALLERY_COUNT = GALLERY_IMAGES.length;
